# Generated by Django 2.2.24 on 2021-07-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aerolinea', models.CharField(max_length=30, verbose_name='Nombre de la aerolínea')),
            ],
            options={
                'verbose_name': 'aerolínea',
                'verbose_name_plural': 'aerolíneas',
                'db_table': 'aerolineas',
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aeropuerto', models.CharField(max_length=30, verbose_name='Nombre del aeropuerto')),
            ],
            options={
                'verbose_name': 'aeropuerto',
                'verbose_name_plural': 'aeropuertos',
                'db_table': 'aeropuertos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción del movimiento')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Fecha del vuelo')),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuelos.Aerolinea', verbose_name='Aerolínea')),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuelos.Aeropuerto', verbose_name='Aeropuerto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuelos.Movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'vuelo',
                'verbose_name_plural': 'vuelos',
                'db_table': 'vuelos',
            },
        ),
    ]
