# Generated by Django 2.2.24 on 2021-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_aerolinea_logo_aerolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='logo_aerolinea',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo de la aerolínea'),
        ),
    ]
