# Generated by Django 2.2.24 on 2021-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_auto_20210725_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='logo_aerolinea',
            field=models.ImageField(blank=True, null=True, upload_to='logos_aerolineas', verbose_name='Logo de la aerolínea'),
        ),
    ]
